/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.client.patient_dms.api;

/*import com.bytatech.ayoos.client.patient_dms.model.ClientBody;
import com.bytatech.ayoos.client.patient_dms.model.Error;
import java.time.OffsetDateTime;
import com.bytatech.ayoos.client.patient_dms.model.PasswordResetBody;
import com.bytatech.ayoos.client.patient_dms.model.PersonBodyCreate;
import com.bytatech.ayoos.client.patient_dms.model.PersonBodyUpdate;
import com.bytatech.ayoos.client.patient_dms.model.PersonEntry;
import com.bytatech.ayoos.client.patient_dms.model.PersonPaging;

import feign.Headers;
import feign.Param;
import feign.RequestLine;

import org.springframework.core.io.Resource;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-05-10T09:58:46.053+05:30[Asia/Kolkata]")

@Api(value = "People", description = "the People API")
public interface PeopleApi{

	@RequestLine("POST /people")
	ResponseEntity<PersonEntry> createPerson(PersonBodyCreate personBodyCreate);

}
*/