/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.client.patient_dms.api;
import feign.RequestLine;
import com.bytatech.ayoos.client.patient_dms.model.Error;
import com.bytatech.ayoos.client.patient_dms.model.SiteBodyCreate;
import com.bytatech.ayoos.client.patient_dms.model.SiteBodyUpdate;
import com.bytatech.ayoos.client.patient_dms.model.SiteContainerEntry;
import com.bytatech.ayoos.client.patient_dms.model.SiteContainerPaging;
import com.bytatech.ayoos.client.patient_dms.model.SiteEntry;
import com.bytatech.ayoos.client.patient_dms.model.SiteMemberEntry;
import com.bytatech.ayoos.client.patient_dms.model.SiteMemberPaging;
import com.bytatech.ayoos.client.patient_dms.model.SiteMembershipApprovalBody;
import com.bytatech.ayoos.client.patient_dms.model.SiteMembershipBodyCreate;
import com.bytatech.ayoos.client.patient_dms.model.SiteMembershipBodyUpdate;
import com.bytatech.ayoos.client.patient_dms.model.SiteMembershipRejectionBody;
import com.bytatech.ayoos.client.patient_dms.model.SiteMembershipRequestBodyCreate;
import com.bytatech.ayoos.client.patient_dms.model.SiteMembershipRequestBodyUpdate;
import com.bytatech.ayoos.client.patient_dms.model.SiteMembershipRequestEntry;
import com.bytatech.ayoos.client.patient_dms.model.SiteMembershipRequestPaging;
import com.bytatech.ayoos.client.patient_dms.model.SiteMembershipRequestWithPersonPaging;
import com.bytatech.ayoos.client.patient_dms.model.SitePaging;
import com.bytatech.ayoos.client.patient_dms.model.SiteRoleEntry;
import com.bytatech.ayoos.client.patient_dms.model.SiteRolePaging;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface SitesApi {

   
	@RequestLine("POST /sites")
     ResponseEntity<SiteEntry> createSite(SiteBodyCreate siteBodyCreate);


 
}
